-- AlterTable
ALTER TABLE "bets" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "games" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "isFinished" SET DEFAULT false;

-- AlterTable
ALTER TABLE "participants" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
